In [84]:
import numpy as np
import pandas as pd
from tensorflow import keras

In [85]:
(train_input,train_target),(test_input,test_target) = keras.datasets.mnist.load_data()

In [86]:
train_data = pd.read_csv('../mnist/train.csv',header=None) # train
test_data = pd.read_csv('../mnist/t10k.csv',header=None) # test
test_data.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
# train_input = train_data.drop(0,axis=1)
train_input = train_data.iloc[:,1:]
# test_input = test_data.drop(0,axis=1)
test_input = test_data.iloc[:,1:]

In [88]:
train_input

,1,2,3,4,5,6,7,8,9,10,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
train_target = train_data[0]
test_target = test_data[0]

In [90]:
train_target

0       5
1       0
2       4
3       1
4       9
       ..
996     6
997     0
998     3
999     6
1000    0
Name: 0, Length: 1001, dtype: int64

In [91]:
# 0~1 까지의 값으로 변경
train_input = train_input/255
test_input = test_input/255

In [92]:
from sklearn.model_selection import train_test_split
train_input,val_input,train_target,val_target = train_test_split(
    train_input,train_target,test_size=0.2,random_state=42
)

In [93]:
train_target.value_counts().sort_index()

0
0    79
1    95
2    78
3    68
4    82
5    75
6    77
7    90
8    73
9    83
Name: count, dtype: int64

In [94]:
# dense층 만들기
dense = keras.layers.Dense(10,activation='softmax',input_shape=(784,))
model = keras.Sequential([dense])
model.compile(loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(train_input,train_target,epochs=5)
model.evaluate(val_input,val_target)

Epoch 1/5

c:\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.2787 - loss: 2.1151
Epoch 2/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step - accuracy: 0.7330 - loss: 1.4579
Epoch 3/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.8074 - loss: 1.1192
Epoch 4/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 540us/step - accuracy: 0.8060 - loss: 0.9379
Epoch 5/5
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.8397 - loss: 0.7672
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.8675 - loss: 0.7200

[0.7560651898384094, 0.8358209133148193]